---
container_image: "nextcloud"
image_tag: "latest"
container_name: "nextcloud"
host_port: 80
container_port: 80
smb_data: "/media/cloud/nextcloud"
service_description: "Nextcloud Container Service"

cron_schedule: "*-*-* 03:00:00"
postgres_db: "nextcloud"
postgres_user: "nextcloud"
postgres_host: "192.168.0.14:5432"
postgres_pwd: "nextcloud"


options: >-
  -v nextcloud-config:/var/www/html
  -v {{ smb_data }}:/var/www/html/data
  -p {{ host_port }}:{{ container_port }}
  -e POSTGRES_HOST={{ postgres_host }}
  -e POSTGRES_DB={{ postgres_db }}
  -e POSTGRES_USER={{ postgres_user }}
  -e POSTGRES_PASSWORD={{ postgres_pwd }}
