---
- name: Deploy Systemd file
  tags:
    - setup
  block:
    - name: Deploy Service
      ansible.builtin.template:
        src: "{{ container_name }}.service.j2"
        dest: "/etc/systemd/system/{{ container_name }}.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - reload systemd
        - restart container
      become: true

    - name: Enable and start service
      ansible.builtin.systemd:
        name: "{{ container_name }}.service"
        enabled: true
        state: started
      become: true

    - name: Deploy Service
      ansible.builtin.template:
        src: "{{ container_name }}-cron.service.j2"
        dest: "/etc/systemd/system/{{ container_name }}-cron.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - reload systemd
      become: true

    - name: Enable service
      ansible.builtin.systemd:
        name: "{{ container_name }}-cron.service"
        enabled: true
      become: true

    - name: Deploy Service
      ansible.builtin.template:
        src: "{{ container_name }}-cron.timer.j2"
        dest: "/etc/systemd/system/{{ container_name }}-cron.timer"
        owner: root
        group: root
        mode: "0644"
      notify:
        - reload systemd
      become: true

    - name: Enable and start service
      ansible.builtin.systemd:
        name: "{{ container_name }}-cron.timer"
        enabled: true
        state: started
      become: true
