---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: restart container
  ansible.builtin.systemd:
    name: "{{ container_name }}"
    state: restarted
  become: true
