---
- name: Remove Nextcloud
  tags:
    - remove
  block:
    - name: Stop Nextcloud Container
      community.docker.docker_container:
        name: nextcloud
        state: stopped

    - name: Delete Nextcloud Container
      community.docker.docker_container:
        name: nextcloud
        state: absent

    - name: Stop MariaDB Container
      community.docker.docker_container:
        name: mariadb
        state: stopped

    - name: Delete MariaDB Container
      community.docker.docker_container:
        name: mariadb
        state: absent
