---
- name: Remove Nextcloud
  tags:
    - remove
    - udpate
  block:
    - name: Stop Nextcloud Container
      community.docker.docker_container:
        name: nextcloud
        state: stopped

    - name: Delete Nextcloud Container
      community.docker.docker_container:
        name: nextcloud
        state: absent
