---
- name: Reset Postgres
  tags:
    - reset
    - never
  block:
    - name: Stop container
      community.docker.docker_container:
        name: "{{ postgres_container }}"
        state: stopped

    - name: Delete container
      community.docker.docker_container:
        name: "{{ postgres_container }}"
        state: absent

    - name: Delete volume
      community.docker.docker_volume:
        name: "{{ postgres_volume }}"
        state: absent

    - name: Launch new Postgres DB
      ansible.builtin.include_tasks: setup.yml
